### ISSUE TITLE
debian下使用报错

### ISSUE THREAD

**Issue by mountainguan** [Baidu-AIP/python-sdk#4]
> Traceback (most recent call last):
>   File "convert.py", line 452, in <module>
>     decide(id)    
>   File "convert.py", line 435, in decide
>     convert_image(res)
>   File "convert.py", line 351, in convert_image
>     source = aipOcr.basicAccurate(get_file_content(filePath), options)
>   File "/usr/local/lib/python2.7/dist-packages/aip/ocr.py", line 110, in basicAccurate
>     return self._request(self.__accurateBasicUrl, data)
>   File "/usr/local/lib/python2.7/dist-packages/aip/base.py", line 98, in _request
>     ), proxies=self._proxies
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
>     timeout=timeout
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
>     body=body, headers=headers)
>   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python2.7/httplib.py", line 1039, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
>     self.endheaders(body)
>   File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 855, in send
>     self.sock.sendall(data)
>   File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
>     return self.connection.sendall(data)
>   File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
>     self._raise_ssl_error(self._ssl, result)
>   File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
>     raise WantWriteError()
> OpenSSL.SSL.WantWriteError

**Comment by iMuduo** [comment]
稳定复现?


原始邮件
发件人:mountainguannotifications@github.com
收件人:Baidu-AIP/python-sdkpython-sdk@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年5月21日(周一) 17:47
主题:[Baidu-AIP/python-sdk] debian下使用报错 (#4)


Traceback (most recent call last):
 File "convert.py", line 452, in 
 decide(id)
 File "convert.py", line 435, in decide
 convert_image(res)
 File "convert.py", line 351, in convert_image
 source = aipOcr.basicAccurate(get_file_content(filePath), options)
 File "/usr/local/lib/python2.7/dist-packages/aip/ocr.py", line 110, in basicAccurate
 return self._request(self.__accurateBasicUrl, data)
 File "/usr/local/lib/python2.7/dist-packages/aip/base.py", line 98, in _request
 ), proxies=self._proxies
 File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
 return request('post', url, data=data, json=json, **kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
 return session.request(method=method, url=url, **kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
 resp = self.send(prep, **send_kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
 r = adapter.send(request, **kwargs)
 File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
 timeout=timeout
 File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
 body=body, headers=headers)
 File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
 conn.request(method, url, **httplib_request_kw)
 File "/usr/lib/python2.7/httplib.py", line 1039, in request
 self._send_request(method, url, body, headers)
 File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
 self.endheaders(body)
 File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
 self._send_output(message_body)
 File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
 self.send(msg)
 File "/usr/lib/python2.7/httplib.py", line 855, in send
 self.sock.sendall(data)
 File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
 return self.connection.sendall(data)
 File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
 self._raise_ssl_error(self._ssl, result)
 File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
 raise WantWriteError()
 OpenSSL.SSL.WantWriteError

**Comment by mountainguan** [comment]
好吧，试了一通发现把依赖卸载重新装了一遍就好了
